// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR4GqYv7JFl-AwWAq3SaVvjiL6qiaXdKY',
    appId: '1:890756936346:web:d90151ef38d5f6fec32523',
    messagingSenderId: '890756936346',
    projectId: 'ludo-cb346',
    authDomain: 'ludo-cb346.firebaseapp.com',
    databaseURL: 'https://ludo-cb346-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ludo-cb346.firebasestorage.app',
    measurementId: 'G-XKKW1B7RDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKGD1ORSQxiy_jEhFfsGBFxmzrBYVagCs',
    appId: '1:890756936346:android:eca31776495092b3c32523',
    messagingSenderId: '890756936346',
    projectId: 'ludo-cb346',
    databaseURL: 'https://ludo-cb346-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ludo-cb346.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXVId99-Wwj2UdK3_WriaDhyH-JKTZxXQ',
    appId: '1:890756936346:ios:b0b202e1700c8c36c32523',
    messagingSenderId: '890756936346',
    projectId: 'ludo-cb346',
    databaseURL: 'https://ludo-cb346-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ludo-cb346.firebasestorage.app',
    iosBundleId: 'com.ludo.game.ai.io',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXVId99-Wwj2UdK3_WriaDhyH-JKTZxXQ',
    appId: '1:890756936346:ios:50d024d36fcd6578c32523',
    messagingSenderId: '890756936346',
    projectId: 'ludo-cb346',
    databaseURL: 'https://ludo-cb346-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ludo-cb346.firebasestorage.app',
    iosBundleId: 'dev.nizwar.ludoFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR4GqYv7JFl-AwWAq3SaVvjiL6qiaXdKY',
    appId: '1:890756936346:web:e48b3fb3707bc796c32523',
    messagingSenderId: '890756936346',
    projectId: 'ludo-cb346',
    authDomain: 'ludo-cb346.firebaseapp.com',
    databaseURL: 'https://ludo-cb346-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ludo-cb346.firebasestorage.app',
    measurementId: 'G-9CYVD3RHVV',
  );

}